### ISSUE TITLE
can we use expressions

### ISSUE THREAD

**Issue by sant527** [alexmojaki/sorcery#10]
I want

```
a = 10
b = 20
dict_of(a,b,a < b)
if a < b:
    ....
```

to return

```
{
"a": 10,
"b": 20,
"a<b":True
}
```

Or can this be possible
```
a = 10
b = 20
dict_of(a,b,"a<10"=a < b)
or
dict_of(a,b,{"a<10":a < b})

if a < b:
   .........
```
currently i am doing

```
print({**dict_of(a,b),**{"a<b": a < b}})
```

**Comment by alexmojaki** [comment]
See args_with_source, print_args, and their implementations.

**Comment by sant527** [comment]
I dont want to print i want dictionary

**Comment by alexmojaki** [comment]
See their implementations.

**Comment by sant527** [comment]
can we use print_args in logging. instead of printing

**Comment by alexmojaki** [comment]
Yes, copy the implementation of print_args and change print to log.

**Comment by sant527** [comment]
ok, thanks
