### ISSUE TITLE
Consider the walrus operator for assigned_names?

### ISSUE THREAD

**Issue by danr** [alexmojaki/sorcery#11]
Hi Alex and sorcerers! Should the walrus operator be considered an assigned name for `assigned_names`?
I think so and this is an example with current and expected output:

```python
from sorcery import spell, print_args

@spell
def lhs(frame_info) -> str:
    return frame_info.assigned_names(allow_one=True)[0]

test = [
    x := lhs(),
    y := lhs(),
]

print_args(x, y, test)
```

Current:

```
x =
('test',)

y =
('test',)

test =
[('test',), ('test',)]
```

Expected:

```
x =
('x',)

y =
('y',)

test =
[('x',), ('y',)]
```

What do you think?

**Comment by alexmojaki** [comment]
Sure, that makes sense. PR welcome.

**Comment by alexmojaki** [comment]
released!

**Comment by danr** [comment]
Wonderful! Thanks for fixing this @cnheider and thanks @alexmojaki for releasing :)
