### ISSUE TITLE
FileNotFoundError when running interactively

### ISSUE THREAD

**Issue by saravanabalagi** [alexmojaki/sorcery#3]
```
from sorcery import dict_of
a=1
b=2
c = dict_of(a,b)
print(c)
```
If I save the script as `mypytest.py` and run it it prints `{'a': 1, 'b': 2}` as expected

But if I run it from python console, it complains
```
Type "help", "copyright", "credits" or "license" for more information.
>>> from sorcery import dict_of
>>> a=1
>>> b=2
>>> c = dict_of(a,b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/sorcery/core.py", line 331, in __call__
    call = FileInfo.for_frame(frame)._plain_call_at(frame, self)
  File "/usr/local/lib/python3.5/dist-packages/sorcery/core.py", line 44, in for_frame
    return file_info(frame.f_code.co_filename)
  File "/usr/local/lib/python3.5/dist-packages/sorcery/core.py", line 31, in __init__
    with tokenize.open(path) as f:
  File "/usr/lib/python3.5/tokenize.py", line 454, in open
    buffer = _builtin_open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '<stdin>'
```

**Comment by saravanabalagi** [comment]
I believe this also has connections with #2, because Jupyter starts an equivalent of interactive console. Any presence of input source while running the code breaks it.

**Comment by alexmojaki** [comment]
Sorcery needs the source code to work, and it's not available in the usual interactive shell. That's why you don't even see a line for it in the traceback.

IPython/Jupyter do make sure the source is placed in linecache, so #2 is now fixed. If you want to use sorcery in a shell, I suggest using the IPython shell.
