### ISSUE TITLE
[Question] Is it possible/easy to implement something like this using sorcery?

### ISSUE THREAD

**Issue by pwwang** [alexmojaki/sorcery#8]
```python
# turn
lambd(X.a + X.b)
# into
lambda X: X.a + X.b
```

Suppose `X.a + X.b` is some valid syntax (proxies). When it is turned into a lambda function, it becomes a valid function body and `X` is replaced by the argument.

This could be implemented inside `lambd`, and it can return the lambda function.

**Comment by alexmojaki** [comment]
Sure, you could get the source like in that recent varname issue, construct the lambda in a string, then eval it.

**Comment by pwwang** [comment]
Is it possible to fetch the AST node and put/eval it in the context as a function body? I mean instead of eval the source code but the AST node. Worried about that source code could be arbitrary.

**Comment by alexmojaki** [comment]
Yes, after all you get the AST node first and get the source code from that. You can eval the node but the node contains the exact same code as the source, it's just as 'dangerous'.

**Comment by pwwang** [comment]
Looks like `args_with_source` fetches the source right with what is passed directly, just like `varname.nameof`.
What if I want to do this:
```python
def func(a, b, c):
  print(args_with_source(a, b, c))

func(1, 2, 3) #gives me
# [('a', 1), ('b', 2), ('c', 3)]

# if I have:
A = 1
B = 2
C = 3
func(A, B, C)

# Is there a way to get:
# [('A', 1), ('B', 2), ('C', 3)]
```
Is a custom spell able to do this?

**Comment by pwwang** [comment]
This is implemented with `executing`.
Just in case if you are curious:

https://github.com/pwwang/pipedy
